###############################################################
# make all target platforms
#
###############################################################


.PHONY: all clean check

#====================================================
# Platform mbed-os
TARGET_PLATFORM:=Linux
all: Linux_all
check: Linux_check
clean: Linux_clean 
include all_tests.mk



